### ISSUE TITLE
Fails horribly when there's no git history

### ISSUE THREAD

**Issue by parkr** [benbalter/jekyll-auth#15]
Running the `:setup` command produces the following if either you (1) have no `.git` folder or (2) have no git history (i.e. `HEAD` is unspecified)

```text
/Users/parkermoore/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/git-1.2.6/lib/git/lib.rb:718:in `command': git diff "-p" "HEAD" "config.ru"  2>&1:fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree. (Git::GitExecuteError)
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
	from /Users/parkermoore/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/git-1.2.6/lib/git/lib.rb:254:in `diff_full'
	from /Users/parkermoore/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/git-1.2.6/lib/git/diff.rb:100:in `cache_full'
	from /Users/parkermoore/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/git-1.2.6/lib/git/diff.rb:106:in `process_full'
	from /Users/parkermoore/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/git-1.2.6/lib/git/diff.rb:64:in `each'
	from ../jekyll-auth/bin/jekyll-auth:13:in `entries'
	from ../jekyll-auth/bin/jekyll-auth:13:in `changed?'
	from ../jekyll-auth/bin/jekyll-auth:58:in `block (3 levels) in <main>'
...
```

**Comment by benbalter** [comment]
Believe this is fixed now. cf https://travis-ci.org/benbalter/jekyll-auth/builds/47567178 to https://travis-ci.org/benbalter/jekyll-auth/builds/47568743 via https://github.com/benbalter/jekyll-auth/pull/50.
